Lesson16
SlevinKelevra/tutu pull request #2
Opened 2017-05-05 13:57 UTC by SlevinKelevra

Вроде сделал задание. Жду замечаний.

2017-05-05 15:54 UTC, webmstk commented on app/models/train.rb
> +    wagons.order(number_id: sort_wagons ? :desc : :asc)
`wagons_sort`, `sort_wagons`, ужс ) сам потом не запутаешься? Может тип сортировки назвать лучше `sort_type` или `sort_from_head`?

2017-05-05 16:36 UTC, SlevinKelevra commented on app/models/train.rb
> +    wagons.order(number_id: sort_wagons ? :desc : :asc)
Когда писал лучше ничего в голову не пришло:)

2017-05-05 17:12 UTC, webmstk commented on app/models/train.rb
> +  end
так ведь наоборот ) да и это же скоуп у `Wagon`, разве нет?

2017-05-05 17:18 UTC, SlevinKelevra commented on app/models/train.rb
> +  end
Не понял замечания....

2017-05-05 17:28 UTC, vkurennov requested changes

2017-05-05 17:28 UTC, vkurennov commented on app/models/railway_station.rb
> +  scope :sort, -> { order('railway_stations_routes.station_number') }
А откуда в railway_station возьмется railway_stations_routes? Чтобы он появился, нужно сделать сначала joins этой таблицы в скоупе, перед тем как делать order

2017-05-05 17:28 UTC, vkurennov commented on app/models/train.rb
> +  end
Что означает флаг sort_wagons, когда он установлен в true? Это сортировка с головы или с хвоста?

2017-05-05 17:28 UTC, vkurennov commented on app/models/wagon.rb
> +  def set_number
Это должен быть приватный метод

2017-05-05 17:28 UTC, vkurennov commented on app/models/wagon.rb
> +  belongs_to :train, class_name: 'Train', foreign_key: :number_id
Изменил бы ты название поля train_id, чтобы путаницы не было

2017-05-05 17:28 UTC, vkurennov commented on app/models/train.rb
> +  end
Очень странная сортировка. Почему она по полу number_id, которая обозначает принадлежность к поезду? И у всех вагонов одного поезда это поле будет иметь одинаковое значение.

2017-05-05 17:28 UTC, vkurennov commented on app/models/wagon.rb
> +      self.number_id = 1
У тебя поле number_id - это не номер вагона у поезда, это поле, которое содержит id поезда. Тебе нужно еще одно поле для номера.

2017-05-06 05:21 UTC, webmstk commented on db/schema.rb
> +    t.integer  "number_train"
зачем это в вагоне? есть связь с поездом, этого достаточно

2017-05-06 05:28 UTC, webmstk commented on app/models/wagon.rb
> +  end
дублирование вычислений
```
def set_number
  max = train.wagons.maximum(:number_wagon)
  self.number_wagon = max ? max + 1 : 1
end
```

2017-05-06 05:32 UTC, webmstk commented on app/models/wagon.rb
> +  scope :sort_number, -> { order(:number_wagon) }
Название скоупа сбивает с толку. Что ты ожидаешь получить, вызвав `wagons.sort_number`? Число сортировки? Назови `ordered` или `sort_by_number`

2017-05-06 05:35 UTC, webmstk commented on app/models/wagon.rb
> +  belongs_to :train, class_name: 'Train', foreign_key: :number_train
у тебя теперь есть нормальное поле `train_id`, убирай `foreign_key` и `class_name`

2017-05-06 05:39 UTC, webmstk commented on app/models/train.rb
> +  def sort_type
если цель метода - получить отсортированные вагоны, почему такое название? )

2017-05-06 05:41 UTC, webmstk commented on app/models/train.rb
> +    wagons.order(number_wagon: :sort_from_head ? :desc : :asc)
а это работает? запускаешь ли ты свой код, товарищ? ) `sort_from_head` - это метод, а не символ, иначе всегда будет `true` возвращаться

2017-05-06 10:29 UTC, vkurennov approved these changes

2017-05-07 20:45 UTC, merged